version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/dockerrun.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/nginx_lb.sh
      timeout: 300
      runas: root

     