version: 0.2

env:
  variables:
    CONF: "prod.conf"

phases:
  install:
    commands:
      - echo "$(lsb_release -cs)"
      - apt-get update -y
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
